# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  helloapi:
    image: helloapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5296:5296
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
